# Generated by Django 5.2.4 on 2025-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('designer', 'Designer'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
